# Generated by Django 6.0.3 on 2026-04-06 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aircraft', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('subsystem', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], max_length=20)),
                ('current_status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Under Analysis', 'Under Analysis'), ('Root Cause Identified', 'Root Cause Identified'), ('Fix In Progress', 'Fix In Progress'), ('Resolved', 'Resolved'), ('Verified Closed', 'Verified Closed')], default='New', max_length=40)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('analysis_findings', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('resolution_action', models.TextField(blank=True)),
                ('severity_score', models.IntegerField(blank=True, null=True)),
                ('resolution_time_hours', models.FloatField(blank=True, null=True)),
                ('component_affected', models.CharField(blank=True, max_length=120)),
                ('environmental_conditions', models.CharField(blank=True, max_length=160)),
                ('flight_phase', models.CharField(blank=True, choices=[('Pre-Flight', 'Pre-Flight'), ('Taxi', 'Taxi'), ('Takeoff', 'Takeoff'), ('Climb', 'Climb'), ('Cruise', 'Cruise'), ('Descent', 'Descent'), ('Landing', 'Landing'), ('Post-Flight', 'Post-Flight')], max_length=40)),
                ('ai_explanation', models.TextField(blank=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='aircraft.aircraft')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_faults', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_faults', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_faults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
