# Generated by Django 6.0.3 on 2026-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=32, unique=True)),
                ('model', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Testing', 'Testing'), ('Maintenance Review', 'Maintenance Review'), ('Operational', 'Operational')], default='Available', max_length=80)),
            ],
            options={
                'ordering': ['tail_number'],
            },
        ),
    ]
