# Generated by Django 6.0.3 on 2026-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aircraft_code', models.CharField(max_length=50)),
                ('subsystem', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor')], max_length=20)),
                ('current_status', models.CharField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('Under Analysis', 'Under Analysis'), ('Root Cause Identified', 'Root Cause Identified'), ('Fix In Progress', 'Fix In Progress'), ('Resolved', 'Resolved'), ('Verified Closed', 'Verified Closed')], default='New', max_length=40)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
